INSERT INTO public.site_config (key, value, label, "group", type) VALUES
  ('hero_badge',          'Premium Fabric Collection',            'Badge Text',              'hero',        'text'),
  ('hero_headline',       'Premium Cutpiece',                     'Headline',                'hero',        'text'),
  ('hero_subheading',     'Per Meter',                            'Subheading',              'hero',        'text'),
  ('hero_description',    'Design your own outfits with our curated collection of high-quality fabrics. From everyday cotton to luxurious silk, find the perfect fabric for your creative vision.', 'Description', 'hero', 'textarea'),
  ('hero_cta1_label',     'Explore Collection',                   'Button 1 Label',          'hero',        'text'),
  ('hero_cta1_url',       '/shop',                                'Button 1 URL',            'hero',        'url'),
  ('hero_cta2_label',     'Our Story',                            'Button 2 Label',          'hero',        'text'),
  ('hero_cta2_url',       '/about',                               'Button 2 URL',            'hero',        'url'),
  ('hero_stat1_number',   '10+',                                  'Stat 1 Number',           'stats',       'text'),
  ('hero_stat1_label',    'Years Experience',                     'Stat 1 Label',            'stats',       'text'),
  ('hero_stat2_number',   '5k+',                                  'Stat 2 Number',           'stats',       'text'),
  ('hero_stat2_label',    'Happy Customers',                      'Stat 2 Label',            'stats',       'text'),
  ('hero_stat3_number',   '100%',                                 'Stat 3 Number',           'stats',       'text'),
  ('hero_stat3_label',    'Quality Assured',                      'Stat 3 Label',            'stats',       'text'),
  ('hero_desktop_image',  'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=1000&q=85', 'Desktop Hero Image', 'hero', 'url'),
  ('hero_mobile_image',   'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=1000&q=85', 'Mobile Hero Image',  'hero', 'url'),
  ('desc_badge',          'Why Choose Us',                        'Badge',                   'description', 'text'),
  ('desc_headline',       'Crafting Dreams,',                     'Headline',                'description', 'text'),
  ('desc_headline_accent','One Fabric at a Time',                 'Headline Accent',         'description', 'text'),
  ('desc_paragraph',      'At Shree Hari Cutpiece, we bring generations of textile expertise to your doorstep with curated fabrics designed for creativity and comfort.', 'Paragraph', 'description', 'textarea'),
  ('desc_point1_title',   'Premium Quality',                      'Point 1 Title',           'description', 'text'),
  ('desc_point1_text',    'Sourced from trusted manufacturers',   'Point 1 Text',            'description', 'text'),
  ('desc_point2_title',   'Sold Per Meter',                       'Point 2 Title',           'description', 'text'),
  ('desc_point2_text',    'Buy exactly what you need',            'Point 2 Text',            'description', 'text'),
  ('desc_point3_title',   'Design Freedom',                       'Point 3 Title',           'description', 'text'),
  ('desc_point3_text',    'Create outfits that are uniquely yours', 'Point 3 Text',          'description', 'text'),
  ('desc_stat_number',    '10+',                                  'Floating Stat Number',    'description', 'text'),
  ('desc_stat_label',     'Years of Excellence',                  'Floating Stat Label',     'description', 'text'),
  ('desc_image1',         '',                                     'Section Image 1',         'description', 'url'),
  ('desc_image2',         '',                                     'Section Image 2',         'description', 'url'),
  ('store_address',       '123, Textile Market, Ring Road, Ahmedabad, Gujarat - 380001', 'Address', 'store', 'textarea'),
  ('store_hours_weekday', 'Monday - Saturday: 10:00 AM - 8:00 PM','Weekday Hours',           'store',       'text'),
  ('store_hours_weekend', 'Sunday: 11:00 AM - 6:00 PM',           'Weekend Hours',           'store',       'text'),
  ('store_phone',         '+91 XXXXX XXXXX',                      'Phone',                   'store',       'text'),
  ('store_email',         'info@shreeharicutpiece.com',           'Email',                   'store',       'text'),
  ('store_maps_url',      'https://maps.google.com',              'Directions URL',          'store',       'url'),
  ('store_embed_url',     'https://www.google.com/maps/embed?...','Maps Embed URL',          'store',       'url')
ON CONFLICT (key) DO NOTHING;
